fos_rest:
    serializer:
        serialize_null: true
    disable_csrf_role: IS_AUTHENTICATED_ANONYMOUSLY
    param_fetcher_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: true }
    view:
        view_response_listener: force
        formats:
            json: true
        mime_types:
            json: ['application/json']
            png:  ['image/png']
            jpg:  ['image/jpeg']
